load("//common:macros.bzl", "stm32_firmware")

stm32_firmware(
    name = "rkh.elf",
    srcs = [
        "rkh.c",
        "rkh_config.c",
        "rkh.h",
        # If you have interrupts specific to example, add them here:
        # "interrupts.c", 
    ],
)