load("//common:macros.bzl", "stm32_firmware")

stm32_firmware(
    name = "stm32_dev.elf",
    srcs = [
        "stm32_dev.c",
        "stm32_dev_config.c",
        "stm32_dev.h",
        # If you have interrupts specific to example, add them here:
        # "interrupts.c", 
    ],
)