load("//common:macros.bzl", "stm32_firmware")

stm32_firmware(
    name = "example.elf",
    srcs = [
        "example.c",
        "example.h",
        # If you have interrupts specific to example, add them here:
        # "interrupts.c", 
    ],
)