load("//common:macros.bzl", "stm32_firmware")

stm32_firmware(
    name = "throttle.elf",
    srcs = [
        "throttle.c",
        "throttle.h",
        # If you have interrupts specific to throttle, add them here:
        # "interrupts.c", 
    ],
)