load("//common:macros.bzl", "stm32_firmware")

stm32_firmware(
    name = "adc_example.elf",
    srcs = [
        "adc_example.c",
        "adc_example_config.c",
        "adc_example.h",
        # If you have interrupts specific to example, add them here:
        # "interrupts.c", 
    ],
)