load("//common:macros.bzl", "stm32_firmware")

stm32_firmware(
    name = "angle_sensor.elf",
    srcs = [
        "angle_sensor.c",
        "angle_sensor_config.c",
        "angle_sensor.h",
        # If you have interrupts specific to example, add them here:
        # "interrupts.c", 
    ],
)