load("//common:macros.bzl", "stm32_firmware")

stm32_firmware(
    name = "spi.elf",
    srcs = [
        "spi.c",
        "spi_config.c",
        "spi.h",
        # If you have interrupts specific to example, add them here:
        # "interrupts.c", 
    ],
)