load("//common:macros.bzl", "stm32_firmware")

stm32_firmware(
    name = "blinky.elf",
    srcs = [
        "blinky.c",
        "blinky_config.c",
        "blinky.h",
        # If you have interrupts specific to example, add them here:
        # "interrupts.c", 
    ],
)