#ifndef VEHICLE_MKVIII_SOFTWARE_LV_VCU_VCU_CONFIG_H_
#define VEHICLE_MKVIII_SOFTWARE_LV_VCU_VCU_CONFIG_H_

#define VCU_MOTOR_ANTICLOCKWISE (0)

#define VCU_APPS1_ADC_CHANNEL (5u)
#define VCU_APPS2_ADC_CHANNEL (6u)
#define VCU_BRAKE_PRESSURE_ADC_CHANNEL (7u)
#define VCU_BRAKE_PRESSURE_FILTERED_ADC_CHANNEL (4u)

#define VCU_APPS1_MIN_COUNTS (30u)
#define VCU_APPS1_MAX_COUNTS (1023u)
#define VCU_APPS2_MIN_COUNTS (20u)
#define VCU_APPS2_MAX_COUNTS (667u)

#endif /* VEHICLE_MKVIII_SOFTWARE_LV_VCU_VCU_CONFIG_H_ */
